services:
  mysql:
    image: mysql:8.4
    container_name: quit_smoking-mysql-prod
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_DATABASE:-quit_smoking}
      MYSQL_ROOT_HOST: "%"
    volumes:
      - mysql_data_prod:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: quit_smoking-redis-prod
    ports:
      - "6379:6379"
    volumes:
      - redis_data_prod:/data
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile
    image: quit_smoking-backend-prod
    container_name: quit_smoking-api-prod
    ports:
      - "8000:8000"
    volumes:
      - backend_storage_prod:/var/www/html/storage
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: ${APP_URL:-http://localhost:8000}
      APP_KEY: ${APP_KEY:-base64:your-app-key-here}

      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE:-quit_smoking}
      DB_USERNAME: ${DB_USERNAME:-root}
      DB_PASSWORD: ${DB_PASSWORD:-root}

      BROADCAST_DRIVER: log
      CACHE_STORE: database
      QUEUE_CONNECTION: database
      SESSION_DRIVER: database
      SESSION_LIFETIME: 120

      SANCTUM_STATEFUL_DOMAINS: ${SANCTUM_STATEFUL_DOMAINS:-localhost:3000,127.0.0.1:3000}
      SESSION_DOMAIN: ${SESSION_DOMAIN:-localhost}
      SESSION_SECURE_COOKIE: ${SESSION_SECURE_COOKIE:-false}
      SESSION_HTTP_ONLY: true
      SESSION_SAME_SITE: lax
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:3000}
      APP_FRONTEND_URL: ${APP_FRONTEND_URL:-http://localhost:3000}
    depends_on:
      - mysql
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8000/api}
    image: quit_smoking-frontend-prod
    container_name: quit_smoking-frontend-prod
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8000/api}
    depends_on:
      backend:
        condition: service_started
    restart: unless-stopped

volumes:
  mysql_data_prod:
  redis_data_prod:
  backend_storage_prod: